services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      app-network:
        aliases:
          - frontend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ~/Downloads:/app/downloads
    networks:
      app-network:
        aliases:
          - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  download_data:

networks:
  app-network:
    driver: bridge
